name: Continuous Integration

on:
  push:
    branches: [ main, dev, staging, prod ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pylint
    
    - name: Run linting
      run: |
        flake8 . || echo "Linting errors detected"
        pylint **/*.py || echo "Pylint warnings/errors detected"
    
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests || echo "Test failures detected"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: python
